import type {
  DashboardSnapshotV1,
  EmailInboxItem,
  WhatsAppDashboardSnapshot,
} from "@/lib/dashboard-types";

export const dashboardFixtureSnapshot: DashboardSnapshotV1 = {
  schemaVersion: "dashboard-snapshot/v1",
  generatedAt: "2026-07-01T08:30:00Z",
  items: [
    {
      id: "wa-open-q3-report",
      source: "whatsapp",
      status: "open",
      title: "Share the Q3 report pack",
      context:
        "A fictional work-chat reminder asks for the latest Q3 report pack before the afternoon review.",
      recommendedAction: "Confirm whether the dashboard should prepare a reply draft.",
      urgency: "high",
      updatedAt: "2026-07-01T08:05:00Z",
      dueAt: "2026-07-01T13:00:00Z",
      displayName: "Alex Rivera",
      metadata: {
        conversation: "Work chat",
        stateReason: "Explicit request awaiting acknowledgement",
      },
    },
    {
      id: "wa-reminded-sync",
      source: "whatsapp",
      status: "reminded",
      title: "Team sync moved to 15:00 tomorrow",
      context:
        "A fictional schedule-change note has already been surfaced once and remains visible as a reminder.",
      recommendedAction: "Keep visible until the schedule note is acknowledged elsewhere.",
      urgency: "normal",
      updatedAt: "2026-06-30T17:45:00Z",
      displayName: "Sam Patel",
      metadata: {
        conversation: "Project Alpha",
        reminderState: true,
      },
    },
    {
      id: "wa-review-wireframes",
      source: "whatsapp",
      status: "uncertain_needs_review",
      title: "Review updated wireframes before Friday",
      context:
        "A fictional design thread references updated wireframes, but the monitor is not confident about whether a response is expected.",
      recommendedAction: "Review the thread context before deciding whether to draft a reply.",
      urgency: "normal",
      updatedAt: "2026-06-29T11:02:00Z",
      dueAt: "2026-07-03T17:00:00Z",
      displayName: "Jordan Lee",
      metadata: {
        conversation: "Design review",
        confidence: "low",
      },
    },
    {
      id: "wa-draft-client-brief",
      source: "whatsapp",
      status: "draft_awaiting_approval",
      title: "Client brief reply draft awaiting approval",
      context:
        "A fictional outbound brief response has been prepared but must remain approval-only in the dashboard.",
      recommendedAction: "Review the draft externally before any send flow is added later.",
      urgency: "normal",
      updatedAt: "2026-07-01T07:40:00Z",
      displayName: "Morgan Chen",
      metadata: {
        conversation: "Client brief",
        draftState: "awaiting approval",
      },
    },
    {
      id: "wa-resolved-history",
      source: "whatsapp",
      status: "resolved_by_history",
      title: "Pull request merge note already resolved",
      context:
        "A fictional engineering follow-up no longer needs attention because later conversation history confirms it was handled.",
      recommendedAction: "No action needed.",
      urgency: "low",
      updatedAt: "2026-06-28T14:30:00Z",
      displayName: "Taylor Kim",
      metadata: {
        conversation: "Engineering",
        resolution: "Later history confirmed merge",
      },
    },
    {
      id: "wa-suppressed-birthday",
      source: "whatsapp",
      status: "suppressed",
      title: "Low-priority social reminder suppressed",
      context:
        "A fictional casual check-in was classified as non-operational and kept only as a suppressed record.",
      recommendedAction: "No action needed.",
      urgency: "low",
      updatedAt: "2026-06-27T18:20:00Z",
      displayName: "Jamie Foster",
      metadata: {
        conversation: "Friends",
        suppressionReason: "Out of scope for operational dashboard",
      },
    },
    {
      id: "email-open-expense-form",
      source: "email",
      status: "open",
      title: "Complete the fictional expense reconciliation form",
      context:
        "A fictional finance email asks for a reimbursement form before the weekly close.",
      recommendedAction: "Confirm whether the form should be completed today.",
      urgency: "high",
      updatedAt: "2026-07-01T07:55:00Z",
      dueAt: "2026-07-01T16:00:00Z",
      displayName: "Finance Ops",
      metadata: {
        labels: "Finance, Inbox",
        actionState: "proposed",
      },
    },
    {
      id: "email-confirm-guest-list",
      source: "email",
      status: "open",
      title: "Confirm the fictional guest list update",
      context:
        "A fictional event-planning email proposes a guest list change that still needs confirmation.",
      recommendedAction: "Confirm whether the proposed update should be accepted.",
      urgency: "normal",
      updatedAt: "2026-07-01T06:40:00Z",
      dueAt: "2026-07-02T10:00:00Z",
      displayName: "Events Desk",
      metadata: {
        labels: "Inbox, Planning",
        actionState: "confirmed",
      },
    },
    {
      id: "email-dismissed-newsletter",
      source: "email",
      status: "dismissed",
      title: "Promotional newsletter dismissed",
      context:
        "A fictional marketing message was intentionally retained only as a dismissed dashboard item.",
      recommendedAction: "No action needed.",
      urgency: "low",
      updatedAt: "2026-06-30T09:10:00Z",
      displayName: "Studio Weekly",
      metadata: {
        labels: "Updates",
        suppressionReason: "Informational only",
      },
    },
  ],
};

export const emailInboxFixtureItems: EmailInboxItem[] = [
  {
    id: "email-inbox-001",
    receivedDateTime: "2026-07-01T07:55:00Z",
    labels: ["Inbox", "Finance"],
    subject: "Expense reconciliation form due today",
    identifiedAction: {
      state: "proposed",
    },
  },
  {
    id: "email-inbox-002",
    receivedDateTime: "2026-07-01T06:40:00Z",
    labels: ["Inbox", "Planning"],
    subject: "Guest list update ready for confirmation",
    identifiedAction: {
      state: "confirmed",
    },
  },
  {
    id: "email-inbox-003",
    receivedDateTime: "2026-06-30T12:15:00Z",
    labels: ["Inbox", "Travel"],
    subject: "Review the fictional rail booking change notice",
    identifiedAction: {
      state: "proposed",
    },
  },
  {
    id: "email-inbox-004",
    receivedDateTime: "2026-06-29T09:30:00Z",
    labels: ["Inbox", "Ops"],
    subject: "Weekly operations recap",
  },
  {
    id: "email-inbox-005",
    receivedDateTime: "2026-06-28T16:05:00Z",
    labels: ["Inbox", "Updates"],
    subject: "Community briefing digest",
  },
];

export const whatsappDashboardFixtureSnapshot: WhatsAppDashboardSnapshot = {
  generatedAt: "2026-07-01T08:30:00Z",
  monitored: [
    {
      id: "wa-conv-orbit-ops",
      kind: "group",
      displayName: "Orbit Launch Ops",
      lastMessageSummary: "Rhea asked whether the launch checklist summary can be reposted before noon.",
      lastMessageAt: "2026-07-01T08:18:00Z",
      listNotes: ["Watching for checklist confirmation", "High activity this morning"],
      historySummary: "Monitored because the team is coordinating a deadline-sensitive launch checklist.",
      timeline: [
        {
          id: "wa-conv-orbit-ops-msg-1",
          speaker: "System note",
          direction: "system",
          summary: "Dashboard marked this group as monitored after repeated checklist mentions.",
          sentAt: "2026-07-01T07:48:00Z",
        },
        {
          id: "wa-conv-orbit-ops-msg-2",
          speaker: "Nina",
          direction: "inbound",
          summary: "Morning all — we still need the final launch checklist summary for the noon huddle.",
          sentAt: "2026-07-01T07:53:00Z",
        },
        {
          id: "wa-conv-orbit-ops-msg-3",
          speaker: "You",
          direction: "outbound",
          summary: "Seen — I am pulling the clean summary into the dashboard notes now.",
          sentAt: "2026-07-01T08:02:00Z",
        },
        {
          id: "wa-conv-orbit-ops-msg-4",
          speaker: "Rhea",
          direction: "inbound",
          summary: "Could you repost that summary here before noon so the room has one link?",
          sentAt: "2026-07-01T08:18:00Z",
        },
      ],
    },
    {
      id: "wa-conv-alex-rivera",
      kind: "direct",
      displayName: "Alex Rivera",
      lastMessageSummary: "Checking whether the fictional Q3 report pack is ready for the client prep call.",
      lastMessageAt: "2026-07-01T08:05:00Z",
      listNotes: ["Awaiting acknowledgement"],
      historySummary: "Direct thread being watched because the request is explicit and time-bound.",
      timeline: [
        {
          id: "wa-conv-alex-rivera-msg-1",
          speaker: "Alex Rivera",
          direction: "inbound",
          summary: "Morning — do you have the latest fictional Q3 report pack handy?",
          sentAt: "2026-07-01T07:41:00Z",
        },
        {
          id: "wa-conv-alex-rivera-msg-2",
          speaker: "You",
          direction: "outbound",
          summary: "I have the revised pack open. Let me confirm the final cover note first.",
          sentAt: "2026-07-01T07:49:00Z",
        },
        {
          id: "wa-conv-alex-rivera-msg-3",
          speaker: "Alex Rivera",
          direction: "inbound",
          summary: "Perfect — I just need it before the 13:00 prep call.",
          sentAt: "2026-07-01T08:05:00Z",
        },
      ],
    },
    {
      id: "wa-conv-design-circle",
      kind: "group",
      displayName: "Design Circle",
      lastMessageSummary: "The team flagged updated wireframes and wants a quick read before Friday.",
      lastMessageAt: "2026-06-30T16:24:00Z",
      listNotes: ["Review requested", "Needs context before response"],
      historySummary: "Monitored because the thread may require a design review reply, but urgency is ambiguous.",
      timeline: [
        {
          id: "wa-conv-design-circle-msg-1",
          speaker: "Mika",
          direction: "inbound",
          summary: "Shared the updated wireframes in the design folder for the Friday walkthrough.",
          sentAt: "2026-06-30T15:58:00Z",
        },
        {
          id: "wa-conv-design-circle-msg-2",
          speaker: "Jules",
          direction: "inbound",
          summary: "Can someone give these a quick operational read before we freeze the agenda?",
          sentAt: "2026-06-30T16:12:00Z",
        },
        {
          id: "wa-conv-design-circle-msg-3",
          speaker: "System note",
          direction: "system",
          summary: "Dashboard marked this thread for review because intent was uncertain.",
          sentAt: "2026-06-30T16:24:00Z",
        },
      ],
    },
    {
      id: "wa-conv-sam-patel",
      kind: "direct",
      displayName: "Sam Patel",
      lastMessageSummary: "Sent a reminder that tomorrow's fictional team sync moved to 15:00.",
      lastMessageAt: "2026-06-30T17:45:00Z",
      listNotes: ["Reminder surfaced once already"],
      historySummary: "Monitored to keep a schedule-change note visible until it is acknowledged elsewhere.",
      timeline: [
        {
          id: "wa-conv-sam-patel-msg-1",
          speaker: "Sam Patel",
          direction: "inbound",
          summary: "Heads up — tomorrow's team sync is now at 15:00 UTC instead of 14:00.",
          sentAt: "2026-06-30T17:31:00Z",
        },
        {
          id: "wa-conv-sam-patel-msg-2",
          speaker: "System note",
          direction: "system",
          summary: "Dashboard kept this reminder visible because it changes an existing schedule.",
          sentAt: "2026-06-30T17:45:00Z",
        },
      ],
    },
  ],
  drafts: [
    {
      id: "wa-conv-morgan-chen",
      kind: "direct",
      displayName: "Morgan Chen",
      lastMessageSummary: "Morgan asked for a short fictional client brief reply before sharing it onward.",
      lastMessageAt: "2026-07-01T07:40:00Z",
      pendingDraftSnippet: "Draft saved: acknowledge the brief, confirm the milestone, and promise a cleaner follow-up note.",
      listNotes: ["Pending draft response", "Approval-only workflow remains out of scope"],
      historySummary: "Opened from Draft responses because a reply draft is waiting for review only.",
      timeline: [
        {
          id: "wa-conv-morgan-chen-msg-1",
          speaker: "Morgan Chen",
          direction: "inbound",
          summary: "Could you shape this into a neat client-ready note before I forward it?",
          sentAt: "2026-07-01T07:11:00Z",
        },
        {
          id: "wa-conv-morgan-chen-msg-2",
          speaker: "System note",
          direction: "system",
          summary: "A fictional reply draft was generated and parked for review only.",
          sentAt: "2026-07-01T07:28:00Z",
        },
        {
          id: "wa-conv-morgan-chen-msg-3",
          speaker: "Morgan Chen",
          direction: "inbound",
          summary: "Thank you — no rush, but I would like to send it later this morning.",
          sentAt: "2026-07-01T07:40:00Z",
        },
      ],
    },
    {
      id: "wa-conv-neighborhood-arts",
      kind: "group",
      displayName: "Neighborhood Arts Board",
      lastMessageSummary: "The board wants a polished follow-up draft after the fictional venue walkthrough.",
      lastMessageAt: "2026-06-30T18:52:00Z",
      pendingDraftSnippet: "Draft saved: thank the group for the walkthrough and propose two timing windows for the next check-in.",
      listNotes: ["Draft response waiting", "Group context included below"],
      historySummary: "Group thread selected from Draft responses because a follow-up note has been drafted but not actioned.",
      timeline: [
        {
          id: "wa-conv-neighborhood-arts-msg-1",
          speaker: "Priya",
          direction: "inbound",
          summary: "Thanks again for visiting the venue — could someone send a tidy recap we can circulate?",
          sentAt: "2026-06-30T18:11:00Z",
        },
        {
          id: "wa-conv-neighborhood-arts-msg-2",
          speaker: "You",
          direction: "outbound",
          summary: "I can prep a concise recap draft for review first.",
          sentAt: "2026-06-30T18:23:00Z",
        },
        {
          id: "wa-conv-neighborhood-arts-msg-3",
          speaker: "System note",
          direction: "system",
          summary: "Draft saved for later approval flow; dashboard remains read-only.",
          sentAt: "2026-06-30T18:52:00Z",
        },
      ],
    },
    {
      id: "wa-conv-jordan-lee",
      kind: "direct",
      displayName: "Jordan Lee",
      lastMessageSummary: "Jordan proposed a concise reply after the fictional workshop schedule changed twice.",
      lastMessageAt: "2026-06-29T11:02:00Z",
      pendingDraftSnippet: "Draft saved: confirm the revised workshop block and ask whether Friday or Monday is preferred for notes.",
      listNotes: ["Draft response pending review"],
      historySummary: "Direct chat selected from Draft responses for schedule-sensitive wording review.",
      timeline: [
        {
          id: "wa-conv-jordan-lee-msg-1",
          speaker: "Jordan Lee",
          direction: "inbound",
          summary: "The workshop block changed again — can we send a cleaner note to reset expectations?",
          sentAt: "2026-06-29T10:31:00Z",
        },
        {
          id: "wa-conv-jordan-lee-msg-2",
          speaker: "System note",
          direction: "system",
          summary: "Suggested reply draft queued for review instead of sending.",
          sentAt: "2026-06-29T11:02:00Z",
        },
      ],
    },
  ],
  followUps: [
    {
      id: "wa-followup-orbit-checklist",
      conversationId: "wa-conv-orbit-ops",
      kind: "group",
      displayName: "Orbit Launch Ops",
      state: "due_now",
      title: "Repost the clean checklist summary before the noon huddle",
      dueAt: "2026-07-01T11:45:00Z",
      relativeDueLabel: "Due now",
      contextSummary: "Latest group message asked for one easy-to-share checklist link before noon.",
    },
    {
      id: "wa-followup-orbit-owners",
      conversationId: "wa-conv-orbit-ops",
      kind: "group",
      displayName: "Orbit Launch Ops",
      state: "proposed",
      title: "Propose a short owner roll-call if checklist confirmations stay fragmented",
      dueAt: "2026-07-01T14:00:00Z",
      relativeDueLabel: "Proposed for this afternoon",
      contextSummary: "Useful only if the team still has scattered confirmations after the huddle.",
    },
    {
      id: "wa-followup-alex-pack",
      conversationId: "wa-conv-alex-rivera",
      kind: "direct",
      displayName: "Alex Rivera",
      state: "due_soon",
      title: "Send the fictional Q3 pack confirmation before the prep call",
      dueAt: "2026-07-01T12:30:00Z",
      relativeDueLabel: "Due soon",
      contextSummary: "Alex said the pack is only needed ahead of the 13:00 prep call.",
    },
    {
      id: "wa-followup-morgan-brief",
      conversationId: "wa-conv-morgan-chen",
      kind: "direct",
      displayName: "Morgan Chen",
      state: "scheduled",
      title: "Review the saved client-brief draft during the late-morning batch",
      dueAt: "2026-07-01T10:30:00Z",
      relativeDueLabel: "Scheduled",
      contextSummary: "The fictional draft exists already; this row tracks the review window, not a send action.",
    },
    {
      id: "wa-followup-arts-recap",
      conversationId: "wa-conv-neighborhood-arts",
      kind: "group",
      displayName: "Neighborhood Arts Board",
      state: "needs_review",
      title: "Check whether the recap draft still matches the latest venue notes",
      dueAt: "2026-07-01T15:00:00Z",
      relativeDueLabel: "Review needed",
      contextSummary: "A fresh walkthrough detail may have changed the tone of the saved recap draft.",
    },
    {
      id: "wa-followup-design-read",
      conversationId: "wa-conv-design-circle",
      kind: "group",
      displayName: "Design Circle",
      state: "scheduled",
      title: "Review the updated wireframes before the Friday walkthrough agenda locks",
      dueAt: "2026-07-03T17:00:00Z",
      relativeDueLabel: "Scheduled",
      contextSummary: "The group asked for a quick operational read, but no explicit response has been promised yet.",
    },
    {
      id: "wa-followup-sam-sync",
      conversationId: "wa-conv-sam-patel",
      kind: "direct",
      displayName: "Sam Patel",
      state: "overdue",
      title: "Confirm the moved sync time landed in the shared calendar note",
      dueAt: "2026-06-30T20:00:00Z",
      relativeDueLabel: "Overdue",
      contextSummary: "The timing change was surfaced yesterday and should already be reflected elsewhere.",
    },
  ],
};
